build:
  image: registry.aliyuncs.com/xueqingxiao/shadowsocks:latest
  when:
    branch: master
publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    registry: registry.aliyuncs.com
    repo: xueqingxiao/shadowsocks
    tag: latest
    file: Dockerfile
    mirror: https://19tyykg1.mirror.aliyuncs.com
deploy:
  ssh:
    host: 47.88.189.75
    user: root
    commands:
      - docker pull registry.aliyuncs.com/xueqingxiao/shadowsocks
      - docker rm -f shadowsocks
      - docker run --name=shadowsocks --restart=always -p 8388:8388 registry.aliyuncs.com/xueqingxiao/shadowsocks -c /etc/shadowsocks.json start