build:
  image: xueqingxiao/shadowsocks:latest
  when:
    branch: master
publish:
  docker:
    username: $$DOCKER_USERNAME
    password: $$DOCKER_PASSWORD
    email: $$DOCKER_EMAIL
    repo: xueqingxiao/shadowsocks
    tag: latest
    file: Dockerfile
deploy:
  ssh:
    host: 47.88.189.75
    user: root
    commands:
      - docker pull xueqingxiao/shadowsocks
      - docker rm -f shadowsocks
      - docker run --name=shadowsocks --restart=always -p 8388:8388 -d xueqingxiao/shadowsocks -s 0.0.0.0 -p 8388 -k $SSPASSWORD -m aes-256-cfb